max_steps = 100  
batch_size = 3
micro_batch_size = 3  
seq_len = 2064  
rollouts_per_example = 3 
async_level = 2  
  
[model]  
name = "Qwen/Qwen3-0.6B"  
  
[ckpt]  
interval = 10 

[sampling]  
max_tokens = 1032 
  
[environment]
id = "reasoning-gym-env"

[environment.args]  
gym = [  
    {name = "sokoban", weight = 1.0, config = {min_w = 6, max_w = 10, min_h = 6, max_h = 10, min_boxes = 1, max_boxes = 10, max_depth = 10}}  
]  

num_train_examples = 500  
num_eval_examples = 100

[wandb] 
name = "reasoning-gym-env-experiment-qwen3-0.6B"  # Changed from 'id' to 'name'  

[eval]  
interval = 20  
environment_ids = ["reasoning-gym-env"]  
num_examples = [100]  
rollouts_per_example = [1]  
eval_base_model = true  
  
[eval.sampling]  
temperature = 0.0  
max_tokens = 4096

